{
    "docs": "https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/compile.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test compile --python 2.7` [[explain](https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/compile.html)] failed with 1 error:", 
            "output": "plugins/module_utils/ncae.py:41:25: SyntaxError: def __init__(self, *, base_url, timeout=60, validate_certs=True):"
        }
    ], 
    "verified": false
}
